# Site settings
title: Paul Melki's Blog!
email: paulmelki@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a M2 student in Statistics & Econometrics at Toulouse School of Economics. 
  I'm also an incoming research intern at IMS Laboratory at Universite de Bordeaux.
  My work and research focus on Deep Learning, Computer Vision and Spatial Analysis.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "paulmelki.github.io" # the base hostname & protocol for your site
github_username:  paulmelki
goodreads_username: paulmelki
linkedin_username: paulmelki

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: "https://plus.google.com/u/0/110288225974212014913"
google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
